version: "3"

services:
  mongo:
    image: "mongo:3.6"
    ports:
      - "27019:27017"

  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
